import type { LayoutTemplate } from '@/types/layout';

export const comparisonThreeLayout: LayoutTemplate = {
  id: 'comparison-three',
  name: 'Three Column Comparison',
  category: 'COMPARISON',
  description: 'Three column comparison for pricing tiers, plan options, or triple feature comparison.',
  thumbnail: '/thumbnails/comparison-three.svg',
  slots: [
    {
      id: 'heading',
      type: 'HEADING',
      label: 'Comparison Title',
      required: true,
      position: { x: 5, y: 3, width: 90, height: 10 },
      constraints: { minLength: 1, maxLength: 120 },
      responsive: {
        mobile: { x: 3, y: 2, width: 94, height: 8 },
      },
      aiHint: 'The overarching title for the three-way comparison.',
    },
    {
      id: 'label1',
      type: 'HEADING',
      label: 'Column 1 Label',
      required: true,
      position: { x: 3, y: 16, width: 29, height: 8 },
      constraints: { minLength: 1, maxLength: 40 },
      responsive: {
        mobile: { x: 3, y: 12, width: 94, height: 5 },
      },
      aiHint: 'Label for the first column. Very short — 1-2 words.',
    },
    {
      id: 'content1',
      type: 'LIST',
      label: 'Column 1 Content',
      required: true,
      position: { x: 3, y: 26, width: 29, height: 68 },
      constraints: { minLength: 1, maxLength: 1000 },
      responsive: {
        mobile: { x: 3, y: 18, width: 94, height: 22 },
      },
      aiHint: 'Bullet points for the first column. 3-5 items.',
    },
    {
      id: 'label2',
      type: 'HEADING',
      label: 'Column 2 Label',
      required: true,
      position: { x: 35, y: 16, width: 29, height: 8 },
      constraints: { minLength: 1, maxLength: 40 },
      responsive: {
        mobile: { x: 3, y: 42, width: 94, height: 5 },
      },
      aiHint: 'Label for the second (middle) column. Very short — 1-2 words.',
    },
    {
      id: 'content2',
      type: 'LIST',
      label: 'Column 2 Content',
      required: true,
      position: { x: 35, y: 26, width: 29, height: 68 },
      constraints: { minLength: 1, maxLength: 1000 },
      responsive: {
        mobile: { x: 3, y: 48, width: 94, height: 22 },
      },
      aiHint: 'Bullet points for the second column. Match the count with other columns.',
    },
    {
      id: 'label3',
      type: 'HEADING',
      label: 'Column 3 Label',
      required: true,
      position: { x: 67, y: 16, width: 29, height: 8 },
      constraints: { minLength: 1, maxLength: 40 },
      responsive: {
        mobile: { x: 3, y: 72, width: 94, height: 5 },
      },
      aiHint: 'Label for the third column. Very short — 1-2 words.',
    },
    {
      id: 'content3',
      type: 'LIST',
      label: 'Column 3 Content',
      required: true,
      position: { x: 67, y: 26, width: 29, height: 68 },
      constraints: { minLength: 1, maxLength: 1000 },
      responsive: {
        mobile: { x: 3, y: 78, width: 94, height: 22 },
      },
      aiHint: 'Bullet points for the third column. Match the count with other columns.',
    },
  ],
  defaultContent: {
    heading: 'Three-Way Comparison',
    label1: 'Basic',
    content1: ['Feature A', 'Feature B', 'Feature C'],
    label2: 'Standard',
    content2: ['Feature A', 'Feature B', 'Feature C', 'Feature D'],
    label3: 'Premium',
    content3: ['Feature A', 'Feature B', 'Feature C', 'Feature D', 'Feature E'],
  },
  minHeight: 350,
  maxHeight: 'auto',
  supportedMediaTypes: [],
  pptxMapping: {
    heading: {
      shapeType: 'textbox',
      x: 0.67,
      y: 0.23,
      w: 12.0,
      h: 0.75,
    },
    label1: {
      shapeType: 'textbox',
      x: 0.4,
      y: 1.2,
      w: 3.87,
      h: 0.6,
    },
    content1: {
      shapeType: 'textbox',
      x: 0.4,
      y: 1.95,
      w: 3.87,
      h: 5.1,
    },
    label2: {
      shapeType: 'textbox',
      x: 4.67,
      y: 1.2,
      w: 3.87,
      h: 0.6,
    },
    content2: {
      shapeType: 'textbox',
      x: 4.67,
      y: 1.95,
      w: 3.87,
      h: 5.1,
    },
    label3: {
      shapeType: 'textbox',
      x: 8.93,
      y: 1.2,
      w: 3.87,
      h: 0.6,
    },
    content3: {
      shapeType: 'textbox',
      x: 8.93,
      y: 1.95,
      w: 3.87,
      h: 5.1,
    },
  },
};
