import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Theme presets — Section 8.2
 * 12 built-in theme presets with full ThemeTokens.
 */
const THEME_PRESETS = [
  {
    name: 'Minimal Light',
    tokens: {
      colors: {
        primary: '#1a1a1a',
        secondary: '#6b7280',
        accent: '#3b82f6',
        background: '#ffffff',
        surface: '#f9fafb',
        textPrimary: '#111827',
        textSecondary: '#6b7280',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#e5e7eb',
        shadow: 'rgba(0,0,0,0.08)',
      },
      typography: {
        fontFamily: { heading: 'Inter', body: 'Inter', mono: 'JetBrains Mono' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'medium',
        lineHeight: '1.6',
        letterSpacing: '-0.01em',
      },
      spacing: {
        sectionPadding: { top: 48, right: 64, bottom: 48, left: 64 },
        slotGap: 24,
        innerPadding: 16,
        sectionGap: 32,
      },
      layout: { maxWidth: 1200, borderRadius: 8, shadowStyle: 'sm', imageStyle: 'rounded' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Minimal Dark',
    tokens: {
      colors: {
        primary: '#ffffff',
        secondary: '#a1a1aa',
        accent: '#60a5fa',
        background: '#18181b',
        surface: '#27272a',
        textPrimary: '#fafafa',
        textSecondary: '#a1a1aa',
        textOnPrimary: '#18181b',
        textOnAccent: '#ffffff',
        border: '#3f3f46',
        shadow: 'rgba(0,0,0,0.3)',
      },
      typography: {
        fontFamily: { heading: 'Inter', body: 'Inter', mono: 'JetBrains Mono' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'medium',
        lineHeight: '1.6',
        letterSpacing: '-0.01em',
      },
      spacing: {
        sectionPadding: { top: 48, right: 64, bottom: 48, left: 64 },
        slotGap: 24,
        innerPadding: 16,
        sectionGap: 32,
      },
      layout: { maxWidth: 1200, borderRadius: 8, shadowStyle: 'md', imageStyle: 'rounded' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Corporate Blue',
    tokens: {
      colors: {
        primary: '#1e3a5f',
        secondary: '#4a6fa5',
        accent: '#2563eb',
        background: '#ffffff',
        surface: '#f0f4f8',
        textPrimary: '#1e3a5f',
        textSecondary: '#4a6fa5',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#cbd5e1',
        shadow: 'rgba(30,58,95,0.1)',
      },
      typography: {
        fontFamily: { heading: 'Georgia', body: 'Inter', mono: 'Fira Code' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'semibold',
        lineHeight: '1.5',
        letterSpacing: '0em',
      },
      spacing: {
        sectionPadding: { top: 56, right: 72, bottom: 56, left: 72 },
        slotGap: 28,
        innerPadding: 20,
        sectionGap: 36,
      },
      layout: { maxWidth: 1100, borderRadius: 4, shadowStyle: 'sm', imageStyle: 'square' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Startup Bold',
    tokens: {
      colors: {
        primary: '#7c3aed',
        secondary: '#f59e0b',
        accent: '#ec4899',
        background: '#faf5ff',
        surface: '#ffffff',
        textPrimary: '#1f2937',
        textSecondary: '#6b7280',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#e5e7eb',
        shadow: 'rgba(124,58,237,0.12)',
      },
      typography: {
        fontFamily: { heading: 'Plus Jakarta Sans', body: 'Inter', mono: 'Fira Code' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.25rem',
          xl: '1.5rem',
          '2xl': '1.875rem',
          '3xl': '2.25rem',
          '4xl': '3rem',
        },
        fontWeight: 'bold',
        lineHeight: '1.4',
        letterSpacing: '-0.02em',
      },
      spacing: {
        sectionPadding: { top: 56, right: 64, bottom: 56, left: 64 },
        slotGap: 32,
        innerPadding: 20,
        sectionGap: 40,
      },
      layout: { maxWidth: 1200, borderRadius: 16, shadowStyle: 'lg', imageStyle: 'rounded' },
      effects: {
        backgroundType: 'gradient',
        gradientAngle: 135,
        gradientStops: [
          { color: '#faf5ff', position: 0 },
          { color: '#fdf2f8', position: 100 },
        ],
      },
    },
  },
  {
    name: 'Nature Green',
    tokens: {
      colors: {
        primary: '#166534',
        secondary: '#65a30d',
        accent: '#eab308',
        background: '#f7fef3',
        surface: '#ecfccb',
        textPrimary: '#14532d',
        textSecondary: '#4d7c0f',
        textOnPrimary: '#ffffff',
        textOnAccent: '#14532d',
        border: '#bbf7d0',
        shadow: 'rgba(22,101,52,0.1)',
      },
      typography: {
        fontFamily: { heading: 'Lora', body: 'Source Sans Pro', mono: 'Fira Code' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'medium',
        lineHeight: '1.7',
        letterSpacing: '0em',
      },
      spacing: {
        sectionPadding: { top: 48, right: 64, bottom: 48, left: 64 },
        slotGap: 24,
        innerPadding: 16,
        sectionGap: 32,
      },
      layout: { maxWidth: 1100, borderRadius: 12, shadowStyle: 'sm', imageStyle: 'rounded' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Creative Neon',
    tokens: {
      colors: {
        primary: '#a855f7',
        secondary: '#06b6d4',
        accent: '#f43f5e',
        background: '#0f0f23',
        surface: '#1a1a3e',
        textPrimary: '#f0f0f0',
        textSecondary: '#a0a0c0',
        textOnPrimary: '#0f0f23',
        textOnAccent: '#ffffff',
        border: '#2d2d5e',
        shadow: 'rgba(168,85,247,0.2)',
      },
      typography: {
        fontFamily: { heading: 'Space Grotesk', body: 'Inter', mono: 'Fira Code' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.25rem',
          xl: '1.5rem',
          '2xl': '1.875rem',
          '3xl': '2.25rem',
          '4xl': '3rem',
        },
        fontWeight: 'bold',
        lineHeight: '1.5',
        letterSpacing: '-0.01em',
      },
      spacing: {
        sectionPadding: { top: 56, right: 64, bottom: 56, left: 64 },
        slotGap: 28,
        innerPadding: 20,
        sectionGap: 36,
      },
      layout: { maxWidth: 1200, borderRadius: 12, shadowStyle: 'lg', imageStyle: 'rounded' },
      effects: {
        backgroundType: 'gradient',
        gradientAngle: 160,
        gradientStops: [
          { color: '#0f0f23', position: 0 },
          { color: '#1a1a3e', position: 100 },
        ],
      },
    },
  },
  {
    name: 'Academic',
    tokens: {
      colors: {
        primary: '#92400e',
        secondary: '#78716c',
        accent: '#b45309',
        background: '#fefce8',
        surface: '#fffbeb',
        textPrimary: '#1c1917',
        textSecondary: '#57534e',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#d6d3d1',
        shadow: 'rgba(28,25,23,0.08)',
      },
      typography: {
        fontFamily: { heading: 'Merriweather', body: 'Source Serif Pro', mono: 'Courier Prime' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'regular',
        lineHeight: '1.8',
        letterSpacing: '0em',
      },
      spacing: {
        sectionPadding: { top: 48, right: 72, bottom: 48, left: 72 },
        slotGap: 20,
        innerPadding: 16,
        sectionGap: 28,
      },
      layout: { maxWidth: 960, borderRadius: 4, shadowStyle: 'none', imageStyle: 'square' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Pitch Deck',
    tokens: {
      colors: {
        primary: '#0f172a',
        secondary: '#334155',
        accent: '#0ea5e9',
        background: '#ffffff',
        surface: '#f1f5f9',
        textPrimary: '#0f172a',
        textSecondary: '#475569',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#e2e8f0',
        shadow: 'rgba(15,23,42,0.08)',
      },
      typography: {
        fontFamily: { heading: 'DM Sans', body: 'Inter', mono: 'JetBrains Mono' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.25rem',
          xl: '1.5rem',
          '2xl': '2rem',
          '3xl': '2.5rem',
          '4xl': '3rem',
        },
        fontWeight: 'bold',
        lineHeight: '1.4',
        letterSpacing: '-0.02em',
      },
      spacing: {
        sectionPadding: { top: 56, right: 64, bottom: 56, left: 64 },
        slotGap: 32,
        innerPadding: 24,
        sectionGap: 40,
      },
      layout: { maxWidth: 1200, borderRadius: 12, shadowStyle: 'md', imageStyle: 'rounded' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Pastel Soft',
    tokens: {
      colors: {
        primary: '#ec4899',
        secondary: '#8b5cf6',
        accent: '#06b6d4',
        background: '#fdf2f8',
        surface: '#fce7f3',
        textPrimary: '#1f2937',
        textSecondary: '#6b7280',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#f9a8d4',
        shadow: 'rgba(236,72,153,0.1)',
      },
      typography: {
        fontFamily: { heading: 'Nunito', body: 'Nunito', mono: 'Fira Code' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'semibold',
        lineHeight: '1.6',
        letterSpacing: '0em',
      },
      spacing: {
        sectionPadding: { top: 48, right: 56, bottom: 48, left: 56 },
        slotGap: 24,
        innerPadding: 16,
        sectionGap: 32,
      },
      layout: { maxWidth: 1100, borderRadius: 16, shadowStyle: 'sm', imageStyle: 'rounded' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Monochrome',
    tokens: {
      colors: {
        primary: '#000000',
        secondary: '#525252',
        accent: '#000000',
        background: '#ffffff',
        surface: '#fafafa',
        textPrimary: '#000000',
        textSecondary: '#525252',
        textOnPrimary: '#ffffff',
        textOnAccent: '#ffffff',
        border: '#d4d4d4',
        shadow: 'rgba(0,0,0,0.06)',
      },
      typography: {
        fontFamily: { heading: 'Playfair Display', body: 'Inter', mono: 'JetBrains Mono' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.25rem',
          xl: '1.5rem',
          '2xl': '2rem',
          '3xl': '2.5rem',
          '4xl': '3.5rem',
        },
        fontWeight: 'bold',
        lineHeight: '1.4',
        letterSpacing: '-0.02em',
      },
      spacing: {
        sectionPadding: { top: 64, right: 80, bottom: 64, left: 80 },
        slotGap: 28,
        innerPadding: 20,
        sectionGap: 40,
      },
      layout: { maxWidth: 1000, borderRadius: 0, shadowStyle: 'none', imageStyle: 'square' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Retro Warm',
    tokens: {
      colors: {
        primary: '#c2410c',
        secondary: '#a16207',
        accent: '#b91c1c',
        background: '#fef3c7',
        surface: '#fde68a',
        textPrimary: '#451a03',
        textSecondary: '#78350f',
        textOnPrimary: '#fef3c7',
        textOnAccent: '#ffffff',
        border: '#d97706',
        shadow: 'rgba(194,65,12,0.12)',
      },
      typography: {
        fontFamily: { heading: 'Libre Baskerville', body: 'Lato', mono: 'Courier Prime' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
        },
        fontWeight: 'medium',
        lineHeight: '1.7',
        letterSpacing: '0.01em',
      },
      spacing: {
        sectionPadding: { top: 48, right: 64, bottom: 48, left: 64 },
        slotGap: 24,
        innerPadding: 16,
        sectionGap: 32,
      },
      layout: { maxWidth: 1100, borderRadius: 8, shadowStyle: 'md', imageStyle: 'rounded' },
      effects: { backgroundType: 'solid' },
    },
  },
  {
    name: 'Gradient Wave',
    tokens: {
      colors: {
        primary: '#7c3aed',
        secondary: '#2563eb',
        accent: '#06b6d4',
        background: '#0f172a',
        surface: '#1e293b',
        textPrimary: '#f8fafc',
        textSecondary: '#94a3b8',
        textOnPrimary: '#0f172a',
        textOnAccent: '#ffffff',
        border: '#334155',
        shadow: 'rgba(124,58,237,0.15)',
      },
      typography: {
        fontFamily: { heading: 'Outfit', body: 'Inter', mono: 'Fira Code' },
        fontSize: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.25rem',
          xl: '1.5rem',
          '2xl': '2rem',
          '3xl': '2.5rem',
          '4xl': '3rem',
        },
        fontWeight: 'bold',
        lineHeight: '1.4',
        letterSpacing: '-0.01em',
      },
      spacing: {
        sectionPadding: { top: 56, right: 64, bottom: 56, left: 64 },
        slotGap: 28,
        innerPadding: 20,
        sectionGap: 36,
      },
      layout: { maxWidth: 1200, borderRadius: 16, shadowStyle: 'lg', imageStyle: 'rounded' },
      effects: {
        backgroundType: 'gradient',
        gradientAngle: 135,
        gradientStops: [
          { color: '#7c3aed', position: 0 },
          { color: '#2563eb', position: 50 },
          { color: '#06b6d4', position: 100 },
        ],
        overlayOpacity: 0.85,
      },
    },
  },
] as const;

async function main() {
  console.log('Seeding theme presets...');

  for (const preset of THEME_PRESETS) {
    await prisma.theme.upsert({
      where: {
        id: preset.name.toLowerCase().replace(/\s+/g, '-'),
      },
      update: {
        name: preset.name,
        tokens: preset.tokens,
        isPreset: true,
      },
      create: {
        id: preset.name.toLowerCase().replace(/\s+/g, '-'),
        name: preset.name,
        tokens: preset.tokens,
        isPreset: true,
        userId: null,
      },
    });
  }

  console.log(`Seeded ${THEME_PRESETS.length} theme presets.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
